### PR TITLE
27.03.2016 Fix Auto-confirm Multiple Confirmations

### PR DESCRIPTION
**Pull request by hyt47**
Pause the timer until the timer actions are done.

### CODE REVIEW

**Comment by DotkaProDotka** [comment]
dont work auto confirm on all accounts . Can be fix pls ?

**Comment by hyt47** [comment]
Did u test this code and it didn't work ?

**Comment by Kasp42** [comment]
I connected an account but I have not shown to confirm the items on the Marketplace

**Comment by hyt47** [comment]
If u added an account now, You will be able to confirm stuff after 7 days.

**Comment by Kasp42** [comment]
7 days have passed.
It not show(confirmations). 
Although the phone can see them

**Comment by hyt47** [comment]
I had this problem. For me the SDA App did not extract the "device_id" from my Android https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47/wiki/Nothing-to-Confirm

**Comment by Kasp42** [comment]
thank you

**Comment by archiegamez** [comment]
Will there be market listing confirmations?

**Comment by sparkdz** [comment]
my problem http://gulfup.cc/ctuohqidku08  plz help me﻿

**Comment by Ramsayrex** [comment]
Can someone please help me

**Comment by Ramsayrex** [comment]
Where is the issue tracker?

**Comment by Ramsayrex** [comment]
@Jessecar96 @geel9 Please help http://pastebin.com/h5Xbzuzw

**Comment by Sufir** [comment]
That fixing multiple autoconfirm https://github.com/Jessecar96/SteamDesktopAuthenticator/pull/216/commits/aa1d1ff18b135d0268fae44a30225499166b1164

**Comment by hyt47** [comment]
I will publish soon a compiled version, Thx

**Comment by Jessecar96** [comment]
Closing this due to it already being fixed in a different way.

**Pull request closed without merging**
