### PR TITLE
Android import

### PR DESCRIPTION
**Pull request by Haarolean**
Hello, I'm sorry for creating PR instead of issue, but:
1. @Jessecar96 just closed all the issues and disabled them at all.
2. He doesn't accept steam friend requests.
3. Tried to contact Geel, that's kinda hard to chat, one message per 3 days. Results:

0:39 - Geel: Try it and see
I tried and as I said it wasn't fixed in commits so the problem still exists, android import doesn't work, there's some issue with path name, I can provide the stacktrace if needed.
20:50 - Geel: I don't have anything to do with the android importing portion of it

The question is are you gonna support this software or what? I can't call Jessecar's actions reasonable.

That was [issue #191](https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/191)

### CODE REVIEW

**Comment by Zeluboba** [comment]
@geel9 @Jessecar96

**Comment by Ankhbileg** [comment]
trade confirmation also doesnt work :( i really need to trade

**Comment by voltij** [comment]
From an outside perspective, it's pretty silly of you guys to not let us use the Issues tab, especially with a program that has such high usefulness but many, MANY bugs. 

Can you explain why you disabled and removed all issues, @geel9 @Jessecar96?

**Comment by PFCKrutonium** [comment]
I have been watching this project for a while, and I may have some insight into why they closed the issues section: The amount of people posting issues that were not issues, The number of times that people did things that the program said not to do, the number of times people posted the same exact thing over and over, the number of people who didn't realize they had to extract the entire archive, not just the main exe.... The list goes on.

**Comment by Ankhbileg** [comment]
my trade confirm doesnt show in confirmation tab...it was working fine before :(

**Comment by voltij** [comment]
@Ankhbileg you aren't helping.

The spam and common issues are a lot to deal with for just two people. This program is a big deal and it should retain the Issues functionality. Maybe just more people need to have moderator access. Or maybe we should drop the "we must answer every question and mark every issue as solved" mindset. When someone posts for help and doesn't get help, they are bound to look for answers elsewhere.

**Comment by Top-Cat** [comment]
This feature was added from a pull request, your chances of getting first party support for it are roughly 0. Chances are it even works on some or most android devices but that's a huge umbrella.

However this project is *open source* so you're welcome to fix the problem and submit an actual pull request or even publish your own version with the fix.

**Comment by mvegter197** [comment]
Credit to: Xven (◡ ‿ ◡ ✿) or 76561198048942187

http://forums.backpack.tf/index.php?/topic/20204-backpacktf-automatic-help-thread/page-65#entry491155

**Comment by Haarolean** [comment]
As a result that @geel9 and @Jessecar96 don't wanna support their code, noone should use this application anymore due possibility of having bugs and security issues. Please use steam application on your phone.

**Comment by voltij** [comment]
Suit yourself. The program is buggy but works.

**Comment by Jessecar96** [comment]
If you want it fixed create a real pull request. This is an open source project and it's no one's job to fix everything in it. Issues were also disabled because of too much spam and help requests there.

**Pull request closed without merging**
