### PR TITLE
Load Accounts after importing from android

### PR DESCRIPTION
**Pull request by hyt47**

### CODE REVIEW

**Comment by llonelly712** [comment]
Bug when i import from android devices
error

**Comment by hyt47** [comment]
yea the app, has a problem, try my mod, https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47
Or u can import manually https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47/wiki/Manually-import-your-Steam-Account-from-Android

**Comment by llonelly712** [comment]
thank you i will try

**Comment by llonelly712** [comment]
Mod is not ok, still error like nomarly.
I try creat maFile, and here when i import.
err 2

**Pull request merged**
