### PR TITLE
Load 'check all accounts' option from settings

### PR DESCRIPTION
**Pull request by sysbeard**

### CODE REVIEW

**Comment by voltij** [comment]
this looks awesome

**Comment by voltij** [comment]
this looks awesome. how many accounts did you check it with? do you think there's a maximum?

if when this gets merged, or maybe if i find time to build this myself, i will let you know how it works :)

**Comment by sysbeard** [comment]
I checked with 5 accounts without problems.
Actually there is something else what has to be fixed.
Authenticator does not handle well RefreshSessionAsync function, because sometimes it throws some network related exception (request timeout, for example).

**Comment by voltij** [comment]
i know that my case is an extreme one, but how many problems do you think this commit will have with ~150 accounts? 

my biggest concern is that "checking for confirmations" would get rate-limited by the steam server. 

my first thought would be coding something like "check 10 accounts every 10 seconds" (or something like this) 

at any rate if SDA ever automatically checks all 150 of my accounts for confirmations, i will find out who is responsible and make it worth their time (by giving them money)

**Comment by Alex1nesko** [comment]
hello. sorry, for my post here. I have a question?
I have windows xp 32 (x86), support max version .NET Framework 4 and vcredist_x86 2013 and 2015.
 link to microsoft [https://msdn.microsoft.com/ru-ru/library/8z6watww%28v=vs.110%29.aspx](url)
When i try to start SDA, i get error "S.... D....A......exe is not a valid Win32 application"
How can to use SDA on winxp32? Have any idea? Can you say, that is possible?
Thank you for you time.
maybe code, below, can do this?
`include 'win32ax.inc' ;We want to launch as 64 bit process

.data
        szMessageCaption        DB "TEST", 0
        szMessageText32         DB "Working on x32.", 0

.code

proc Our64Proc ;x64 bit process code 
     use64
        CALL @F
        DB "Generated using x64 ASM code.", 0
@@:
        POP RAX
        MOV RCX, RAX

     use32
        RETF
endp

start:
        ;invoke DebugBreak ;Used for debugging

        MOV AX, CS
        CMP AL, 1Bh ;1Bh for 32 bits native, 33h if 64 bits native, 23h for wow64
        JE Its32BitsNative
        CMP AL, 33h
        JE ExitCode

        XOR ECX, ECX
        CALL 33h:Our64Proc

        invoke MessageBox, 0, ECX, szMessageCaption, MB_OK
        JMP ExitCode

Its32BitsNative:
        invoke MessageBox, 0, szMessageText32, szMessageCaption, MB_OK


ExitCode:
        invoke ExitProcess, 0
.end start
`

code from here [https://forum.zone-game.info/showthread.php?t=27111&page=5](url)

**Comment by voltij** [comment]
@sysbeard @geel9 

I have 5 accounts in my list of SDA

I have all Settings options checked and timer set to 15 seconds

My manifest shows: 

> ..."periodic_checking":true,"periodic_checking_interval":15,"periodic_checking_checkall":true,"auto_confirm_market_transactions":true,"auto_confirm_trades":true}

I cannot get auto confirmation of trades for all accounts to work properly.

I'm willing to help troubleshoot if someone can assist me. Also willing to pay/donate for assistance.

**Comment by hyt47** [comment]
@Alex1nesko to run on windows Xp x32 use https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47

**Pull request merged**
