### PR TITLE
Autoconfirm for all acounts fix

### PR DESCRIPTION
**Pull request by Sufir**
Autoconfirm for all acounts dont work. Confirming only selected account `currentAccount`.

### CODE REVIEW

**Comment by Sufir** [comment]
I think popup for multiple don't work too, but I not use it.

**Comment by wootpeng** [comment]
Need this fix but not sure how to implement it. Hoping for an official release.

**Comment by Ps1d3r** [comment]
Hello
I'm to post here, but i have nowhere else to turn to... I keep getting that my encryption key is wrong although i'm sure i'm typing it correctly. This has happened before, and all i did was replace the maFiles with one i have from previous versions. This time is not working, and i have no idea how to solve this. I really need SDA working since i have no other way to confirm trades or get the codes.
THanks

**Comment by toshex** [comment]
I also don't know whare your support is - can't open an issue so here goes:

Can't see confirmations, can't refresh session and can't relogin due to captcha always popping up even though I enter it correctly.

Checked the maFile and no error in it. Can you please help?

**Comment by wootpeng** [comment]
Guess this project is abandoned?

**Comment by hyt47** [comment]
@wootpeng you can use this https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47 I included this fix

**Comment by wootpeng** [comment]
@hyt47 Thanks! Will give it a shot.

**Comment by sirwatt** [comment]
This pull request works for market confirmations but it breaks the trades Popup.
If i send trade from account1 to account 2, and have account3 selected it will show that I sent trade from account3 to account2 and the accept button won't accept the trade.
Only works if i have the account1 selected and now it shows the correct trade.

**Comment by tambu22** [comment]
http://pastebin.com/VE7E66Kx

error on accepting market confirmations, since the new steam app update.

**Comment by fibixer** [comment]
I'm getting error when I'm trying to put my items on the Market. 
Here is the log: http://pastebin.com/8xWkGwC2

**Comment by dazach** [comment]
The problem is:

`Regex confIDRegex = new Regex("data-confid=\"(\\d+)\"");`
`Regex confKeyRegex = new Regex("data-key=\"(\\d+)\"");`
`Regex confDescRegex = new Regex("<div>((Confirm|Trade with|Sell -) .+)</div>");`

There are two "data-confid" and "data-key" for each market listing, but only one description.

That's why it throws ArgumentOutOfRangeException.

**Comment by tambu22** [comment]
but i really dont know how to change it and compile, so i ll w8 the update. happy to know I'm not the only1

**Comment by Sufir** [comment]
@Jessecar96 can u accept this small fix please? Thnx.

**Pull request closed without merging**
