### PR TITLE
Trade confirmations says that there are no confirmations to make

### PR DESCRIPTION
**Pull request by TCarneiro91**
Hey, i have done everything right, i imported my account info from my android phone, i also had everything working fine, the SG codes, everything, but when i DO have some trade/market confirmations to make, the SDA shows me that  there is nothing to confirm. i forces the session in the main form, and redownloaded and started all the process again, nothing worked

### CODE REVIEW

**Comment by moonbeads** [comment]
same problem, except when i hit "force session refresh" it always returns an error

**Comment by svhero658** [comment]
I also have this problem,trade confirmation window shows nothing to confirm but actually it has.I imported my account form android phone.

**Comment by Netifriik** [comment]
Same issue, also imported from Android. Any news?

**Comment by voltij** [comment]
Please consider posting a thread about this on https://www.reddit.com/r/SteamDesktopAuth/

(Instead of using a pull request to do so)

**Comment by svhero658** [comment]
Problem solved.Get your device id from steam.uuid.xml and sha1 it.Find device_id term in your mafile and replace its value with your result.That's all done.

**Comment by Jessecar96** [comment]
Not sure why there are commits on this.

**Comment by thecoinsdev** [comment]
I found an easy solution for this problem. If you are getting an error every time you try to refresh your session, click "Selected Account" then "Login Again" and login. It fixed this problem for me and I didn't have to deactivate/reactivate steam guard or anything. I can now refresh the sessions and accept trade confirmations as expected. I think this is caused by an expired session in SDA. I only had this problem after not using the authenticator for a while.

**Comment by hyt47** [comment]
This problem appears if u don't use your SDA for some time

I got the same problem! Your solution doesn't work for me.
I have an account for testing on my Android phone, and I didn't used it for ~ 2 months. 

I imported the account to SDA and i wanted to make a trade, SDA doesn't show me any confirmations, I tried `Force session refresh` and `Login again`, it doesn't work.

 I can see the confirmation on my phone, I can accept it there, but first I want to see if this problem can be fixed. 
I fell like something is missing from SDA, or there is a bug somewhere...

**Comment by hyt47** [comment]
after I extracted the account from android, the data is incomplete `"device_id":"ERROR",` , now I must see how to fix that

**Comment by mohammadg** [comment]
I had the same issue, "device_id" was set to ERROR.
I manually recovered the device ID using instructions here: https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47/wiki/Nothing-to-Confirm

And it now works fine.

**Pull request closed without merging**
