### PR TITLE
Data Encryption

### PR DESCRIPTION
**Pull request by holeydood3**
Added a class to easily handle data encryption. This particular class
utilizes PBKDF2 for key derivation, and AES-256 for encryption. All data
passed into and out of this class is encoded in base64 so none of the
data gets broken.

### CODE REVIEW

**Comment by holeydood3** [comment]
Yeppers. It's basically a movie scene where you need everyone to enter their keys at the same time to deactivate the bomb. If one piece is missing the whole thing blows. Salt and IV are totally allowed to be seen publicly, so no worries about saving it as text. They're just necessary to block brute force and rainbow tables as much as possible.

**Comment by josefc** [comment]
Wouldn't it be easier to use System.Security.Crytography's ProtectedMemory functions? You don't need to worry about storing your salt and IV
````
public static void EncryptData(ref byte[] buffer, MemoryProtectionScope scope)
{
	// Check our buffer for data
	if (buffer.Length <= 0)
		throw new ArgumentException("Buffer");
	if (buffer == null)
		throw new ArgumentNullException("Buffer");

	PadToMultipleOf(ref buffer, 16);

	// Encrypt the buffer. This function doesn't return the data
	// as it is stored in the same byte array as the original
	ProtectedMemory.Protect(buffer, scope);
}
````

Keys are handled by the OS and are stored for the current user. To encrypt a string you can run this code

````
public static byte[] EncryptString(string input)
{
	byte[] toEncrypt = Encoding.Unicode.GetBytes(input);
	EncryptData(ref toEncrypt, MemoryProtectionScope.SameLogon);
	return toEncrypt;
}

````

I've got this code written but @holeydood3 got this posted first

**Comment by holeydood3** [comment]
ProtectedMemory is a good one to use, but I worry about the fact that if an attacker is inside their computer (which is needed in the first place to take the data if was just saved as plaintext), then they effectively have the credentials as the user to decrypt the data(admittedly it would take a very intelligent attacker). At least with this an additional password only known by the user is required. My way might be overkill though.

**Comment by josefc** [comment]
It really depends on if you want a frictionless experience for users and having the OS handle the encryption or if you want to handle the encryption, storage of credentials and prompting a user for a password each time

**Comment by holeydood3** [comment]
Agreed, that's a balance you have to strike. In a perfect world the user could click a checkbox on the program that lets them choose, but then that starts adding additional complexity.

**Pull request merged**
