### PR TITLE
added saFile; settings for system tray icon; confirmation list; verify accounts at startup, In popup you can choose any confirmation

### PR DESCRIPTION
**Pull request by hyt47**
- Fixed a few small stuff in the GUI
- Added alot of options in the settings
  - System Tray:(choose)
    - Close button minimizes the app to tray
	  - if activated, Quit button will appear under X button for Fast Exit, if u ever need it

    - minimize button minimizes the app to tray
    - none - show try icon
    - none - hide tray icon

  - Poput Notification max Limit increased to 99999 sec
    - Added CheckBox Check all accounts for confirmations @pipe01

  - Confirmation List
    - You can enable it and a button will appear on the main GUI
	- I also added a refresh button for Confirmation List

  - Auto check for updates on / off

- maFile replaced with saFile
  - you now have more security with encrypted accounts
  - IV & Salt & Account data all are stored inside the saFile
  - IV & Salt have been removed from manifest
  - using saFiles now you can remove an account from manifest
  - you can import it back easy even if is encrypted (if u know the passkey)

- you can still import your old maFiles and they will be converted to saFile
- You can export saFile as maFile

- at startup verify accounts saFile & manifest & if a problem is detected it will try to fix it (this is a safeguard)
     - if a problem is detected and the app can't fix it it will unlink the accounts from manifest and move them to folder "SDA Folder/accounts to import again"

- accounts removed from manifest now are stored in folder: accounts removed from manifest

- Fixed typing on the accounts list @pipe01 https://github.com/pipe01/SteamDesktopAuthenticator/commit/2657a6e3b47870b07e2e9b29864cff5b901fdc16
- Added option to check for all accounts each X seconds @pipe01 https://github.com/pipe01/SteamDesktopAuthenticator/commit/bf7d619113ccae6a9e4797cf0d99d8af0e0d108f

- WelcomeForm it a bit of a mess, but it works

### CODE REVIEW

**Comment by pipe01** [comment]
Really nice work! I have to try it out.

**Comment by hyt47** [comment]
Thx

**Comment by Jessecar96** [comment]
Woah dude, make your commit messages descriptive. Not just "Update filename"

**Comment by Jessecar96** [comment]
Also any changes to maFiles will not be accepted on this project. If you want to update that make a pull request on SteamAuth, where they are handled.

**Comment by hyt47** [comment]
saFile only encrypts differently than maFile, it still has the same data when is not encrypted

for example when is encrypted it looks like:
encryption_iv_code<next_string_of_data>encryption_salt<next_string_of_data>maFileDataEncrypted

when is not encrypted: maFileData

**Comment by hyt47** [comment]
If I revert back to maFile
I can try to modify the description script to recognize if the file is encrypted differently, by searching in maFile for &lt;ext_string_of_data>, and if it's found to don't read the manifest value IV,salt 

But this may result in errors if the users tries to use my modified maFile encrypted in an older app 

I added .saFile to avoid incompatibility issues, in case someone copies the old folder maFiles in the app

And the user has the option to import/export maFiles & saFiles(for newer versions of the app)

**Comment by hyt47** [comment]
Or if you want I can revert back the part about saFile, and re add maFile, and we can update the rest.

But if an user has his account encrypted & he loses the manifest file (IV salt), he needs to remove the authenticator, saFile was created to avoid that

**Comment by hyt47** [comment]
**Popup changes:**
  - Fixed x Button for Popup
  - Now you can choose what confirmation you want to accept ( I added buttons: next & back so u can navigate between confirmations)
     - Button Next will be activated if u have more than 1 Confirmation waiting
     - Button Back will be activated after you navigate to the second, confirmation

  - Popup GUI has been changed

**Comment by hyt47** [comment]
Copy button fixed, (if the value is null don't do nothing)

**Pull request closed without merging**
