### PR TITLE
Fix work on Windows 7

### PR DESCRIPTION
**Pull request by alexander7550**

### CODE REVIEW

**Comment by jwcloverain** [comment]
use http is not safe,for this error check if the system has installed the kb3140245 update?
see https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392

**Comment by kasavaros** [comment]
Try this fix for win 7 https://download.microsoft.com/download/0/6/5/0658B1A7-6D2E-474F-BC2C-D69E5B9E9A68/MicrosoftEasyFix51044.msi

**Comment by kasavaros** [comment]
> use http is not safe,for this error check if the system has installed the kb3140245 update? see https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392

This update and fix did not help me.
But there is another software - Tradeonsda and it works on Windows 7 https://github.com/TradeOnSolutions/Steam-Desktop-Authenticator

**Comment by Jessecar96** [comment]
I don't like this solution. Loading the image over plain http is not secure and can leak info about someone using SDA. A better solution would be to get the PictureBox to use TLS 1.2, if possible.

**Comment by chinap** [comment]
use this method?
see：https://stackoverflow.com/questions/24797485/how-to-download-image-from-url
tls

**Pull request closed without merging**
