### PR TITLE
Secondary GUI Compact added, A lot of settings added, added button Confirmations List (as an option), Minimise to tray options, GUI Confirmation Popup updated

### PR DESCRIPTION
**Pull request by hyt47**
- Fixed a few small stuff in the GUI
- Added a secondary GUI more compact
- the app runs only once & if u start the app again & the first instance is in the tray or taskbar, it will be activated
- Added alot of options in the settings
  - System Tray:(choose)

    - Close button minimizes the app to tray
      - if activated, Quit button will appear under X button for Fast Exit, if u ever need it

    - minimize button minimizes the app to tray
    - none - show try icon
    - none - hide tray icon

  - Poput Notification max Limit increased to 99999 sec
  - Added CheckBox Check all accounts for confirmations @pipe01

  - Confirmation List with refresh button
    - You can enable it and a button will appear on the main GUI

  - Auto check for updates on / off
  - Fixed typing on the accounts list @pipe01 https://github.com/pipe01/SteamDesktopAuthenticator/commit/2657a6e3b47870b07e2e9b29864cff5b901fdc16
  - Added option to check for all accounts each X seconds @pipe01 https://github.com/pipe01/SteamDesktopAuthenticator/commit/bf7d619113ccae6a9e4797cf0d99d8af0e0d108f

- Accounts list is disabled while Refreshing session...
- Popup Confirmation:
  - the x button works (fixed) but i removed it
  - GUI Changed
  - Button's next & back added, now you can choose the confirmation you want to accept first
  - The GUI has 2 borders, you can change that in settings

Disabled List
----
disabled list

GUI Default with button Confirmations List activated
---
gui 1 simple a1

GUI Compact with button Confirmations List activated
---
gui 2 compact b

Settings
---
settings

Popup
---
popup 1 confirmation

Next Pull Request will be:
----------------------------------
- Added Encryption v2 for .maFile
- The App will detect the old encryption & it can import it
- The app will verify your accounts data at startup (this code is a safeguard, it shood never find a problem & give you a msg)
  - if a problem is detected the app will try to fix your accounts

- Added FlexibleMessageBox http://www.codeproject.com/Articles/601900/FlexibleMessageBox-A-flexible-replacement-for-the
  - used by the script that verifyes you accounts

- The encrypted files will not be backward compatible with older app versions
- You will have the option to import your old files from an older SDA app (originally created for your startup form)
- maFile encryptyon format: v2&lt;next_string_of_data>salt&lt;next_string_of_data>IV&lt;next_string_of_data>SteamDataEncrypted
  - &lt;next_string_of_data> is the separator, used to split the string and extract data

- Files removed from manifest are moved to folder: 'accounts removed from manifest'

### CODE REVIEW

**Comment by hyt47** [comment]
@Jessecar96 do you want me to close this "pull request"  and create "pull requests" (1 at a time) with smaller chunks of code?

**Comment by Skimminok** [comment]
Can you add automatic confirmation of creating listing as an option? After entering new rules since March 9, it takes a lot of time.

**Comment by routemasters** [comment]
@Skimminok nothing new was added since march 9th, only hold up periods increased to 15 days.

**Comment by Skimminok** [comment]
@routemasters now need confirmating all items, even lower then 3$

**Comment by mcrmarcelo** [comment]
So, we can import an Account from BlueStacks or only from a Android device, anyone can help ?
Thanks

**Pull request closed without merging**
