### PR TITLE
Added PhoneBridge to extract existing account from an android phone

### PR DESCRIPTION
**Pull request by pipe01**
Implemented a way to extract an existing Steam guard account from an Android phone.
It will:
- Check if ADB exists in either in PATH variable or executable folder by running "ADB.exe"
- Check if any device is avaiable by running "adb get-state"
- Check if the device is rooted by executing "su"  on the device
- Check if the Steam app is installed
- Pull the JSON file called "Steamguard-X" (X being the user's SteamID64) in "/data/data/com.valvesoftware.android.steam.community/files/"
- If the device isn't rooted, an alternative method will be used (TODO: explain)
- Return the unserialized SteamGuardAccount object

What I still don't know is how to implement this to the rest of the program. I tried to save it with a Manifest but some error occurs.
Another thing that I dont know if it's important or not is that the JSON doesn't contain the "Session" value, which may be required for some things.

AD: By the way, this is a simplified version of my library ADB.net, which contains more functionality to function like an ADB wrapper. It's still in early development, but you may wanna have a look.

### CODE REVIEW

**Comment by Jessecar96** [comment]
This looks really cool. I didn't even know it would be possible to pull it without root, but adb backup was a great idea.

**Comment by Paaashka** [comment]
Thank you mate! That adb backup method works great. Saved me a lot of time and guarantee on my phone :)

**Comment by pipe01** [comment]
Thanks! I'm looking forward to implement this correctly, but im still stuck.

**Comment by geel9** [comment]
How does this handle multiple accounts on the same phone?

**Comment by pipe01** [comment]
Well, I didn't even know it was possible to have more than one account on the same phone, but i guess another Steamguard-X file will be created, so i'll have to be able to select the one that you want.

**Comment by pipe01** [comment]
Yup, just tested it and it creates another file.

**Comment by pipe01** [comment]
I think that will do the job, but only to the root method. The no-root method should be able to do so as well later

**Comment by ntlittle** [comment]
The root method will be enough for most android users. And it will be SUPER usefull feature!

**Comment by pipe01** [comment]
Yeah, thanks!

**Comment by terryhau** [comment]
I think what you want to do is at "case LoginResult.Need2FA:", instead of continuing, you want to pop up a form to input the mobile auth code. That will allow a successful login, and give you the session. Then you want to skip the whole linker part, because the account is already linked. Then, the only thing you're missing is the deviceID which is not provided in the file extracted from Android. You may have to pull this from the phone some how.

**Comment by terryhau** [comment]
Just did a quick test and it seems to be working.
Fill in the blanks in the function below and execute it.
It will ask for mobile steam guard code. Get it from your phone and enter it.
At this point I disconnected my phone from the internet in case having multiple authenticators simultaneously causes problems.
Your account should now be imported and working. (may have to reload the main form to see it, depending on where you execute the code from)
If you want to stop using the authenticator on Android, I think the best way is to uninstall/reinstall the Steam app. Don't remove the authenticator from inside the Steam Android app, since that will invalidate the link you just imported.

    private void doItToolStripMenuItem_Click(object sender, EventArgs e)
    {
        SteamGuardAccount acc = new SteamGuardAccount();
        acc.SharedSecret = "<get from SteamGuard-%SteamID64>";
        acc.SerialNumber = "<get from SteamGuard-%SteamID64>";
        acc.RevocationCode = "<get from SteamGuard-%SteamID64>";
        acc.URI = "<get from SteamGuard-%SteamID64>";
        acc.ServerTime = <get from SteamGuard-%SteamID64>;
        acc.AccountName = "<get from SteamGuard-%SteamID64>";
        acc.TokenGID = "<get from SteamGuard-%SteamID64>";
        acc.IdentitySecret = "<get from SteamGuard-%SteamID64>";
        acc.Secret1 = "<get from SteamGuard-%SteamID64>";
        acc.Status = 1;
        acc.DeviceID = "<get from steam.uuid.xml>";
        acc.FullyEnrolled = true;

        string username = "<steam username>";
        string password = "<steam password>";

        UserLogin mUserLogin = new UserLogin(username, password);
        LoginResult response = LoginResult.BadCredentials;

        while ((response = mUserLogin.DoLogin()) != LoginResult.LoginOkay)
        {
            switch (response)
            {
                case LoginResult.NeedEmail:
                    InputForm emailForm = new InputForm("Enter the code sent to your email:");
                    emailForm.ShowDialog();
                    if (emailForm.Canceled)
                    {
                        this.Close();
                        return;
                    }

                    mUserLogin.EmailCode = emailForm.txtBox.Text;
                    break;

                case LoginResult.NeedCaptcha:
                    CaptchaForm captchaForm = new CaptchaForm(mUserLogin.CaptchaGID);
                    captchaForm.ShowDialog();
                    if (captchaForm.Canceled)
                    {
                        this.Close();
                        return;
                    }

                    mUserLogin.CaptchaText = captchaForm.CaptchaCode;
                    break;

                case LoginResult.Need2FA:
                    emailForm = new InputForm("Enter mobile Steam Guard code:");
                    emailForm.ShowDialog();
                    if (emailForm.Canceled)
                    {
                        this.Close();
                        return;
                    }

                    mUserLogin.TwoFactorCode = emailForm.txtBox.Text;
                    break;

                case LoginResult.BadRSA:
                    MessageBox.Show("Error logging in. Steam returned \"BadRSA\".");
                    this.Close();
                    return;

                case LoginResult.GeneralFailure:
                    MessageBox.Show("Error logging in. Steam returned \"GeneralFailure\".");
                    this.Close();
                    return;
            }
        }

        acc.Session = mUserLogin.Session;
        Manifest.GetManifest().SaveAccount(acc, false, null);
        MessageBox.Show("Mobile authenticator successfully linked. Please write down your revocation code: " + acc.RevocationCode);
    }

**Comment by pipe01** [comment]
Wow, thank you a lot! I'm so gonna implement that when I can.

**Comment by pipe01** [comment]
Now you can import your account from your phone! It doesn't need to be unlinked from your phone, so you can have both your phone and desktop at the same time!

**Comment by Jessecar96** [comment]
Tested it with my rooted Nexus 6P and it works great. Thanks for this!

**Comment by pipe01** [comment]
No problem! By the way, I haven't tried to remove authenticator with an account imported from a phone, so I don't know what would happen.

**Comment by silentguy256** [comment]
I can't create an issue in this project, so I'll write here cause it's most closely related. I have an unrooted phone with working debugging, cut the import process crashes. looking at this, i would assume that for some reason it fails to get the file and then tries to access it, cause the error I get is 

System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\XXX\SDA\steamguard" konnte nicht gefunden werden.

I also see it create an empty android backup fule, so I guess that is somehow related

**Pull request merged**
